# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credit_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportId', models.CharField(max_length=30)),
                ('custId', models.CharField(max_length=18)),
                ('custName', models.CharField(max_length=50)),
                ('queryTime', models.DateTimeField()),
            ],
        ),
    ]
